#!/usr/bin/env python

import sys
import os
import optparse
import logging
import pprint    
import mapzen.whosonfirst.diff
import json

if __name__ == '__main__':

    opt_parser = optparse.OptionParser()

    opt_parser.add_option('-s', '--source', dest='source', action='store', default=None, help='Directory to read files from')

    opt_parser.add_option('-v', '--verbose', dest='verbose', action='store_true', default=False, help='Be chatty (default is false)')
    options, args = opt_parser.parse_args()

    if options.verbose:	
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)

    source = options.source

    if not source:
        raise Exception, "Missing source"

    source = os.path.abspath(source)

    if not os.path.exists(source):
        raise Exception, "Source does not exist"


    diff = mapzen.whosonfirst.diff.compare(source=source)

    for id in args:

        report = diff.report(id)
        json.dump(report, sys.stdout, indent=2)
